weights:
  integrations_apis: 12
  customization_extensibility: 10
  usability_admin: 10
  analytics_ai: 10
  security_compliance: 10
  sales_core: 15
  service: 7
  marketing: 7
  pricing_tco: 9
  data_migration_portability: 5
  support_ecosystem_viability: 5
scales:
  0: "absent"
  3: "adequate"
  5: "excellent"
